version: '3'

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
  db2:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
